thirvusoft/building_block_retail

sgp/hooks.py
sgp/sgp/custom/py/site_work.py
sgp/sgp/utils/projects/site_work/site_work.py

create advance amount for a customer in site work

Site advance

---

sgp/hooks.py
sgp/sgp/custom/js/quotation.js
sgp/sgp/custom/py/workflow.py
sgp/sgp/function_calling.py
sgp/sgp/utils/crm/quotation/quotation.py

Custom field supervisor and workflow -->draft --> Approve --> Approved

custom in quotation and workflow

---

sgp/sgp/custom/js/site_work.js
sgp/sgp/utils/projects/site_work/site_work.py
sgp/sgp/utils/selling/delivery_note/delivery_note.py

Delivery Note and Site work fixes

Delivery Note and Site work fixes

---

sgp/sgp/custom/py/sales_order.py
sgp/sgp/custom/py/site_work.py
sgp/sgp/doctype/additional_costs/additional_costs.json
sgp/sgp/doctype/compound_wall/compound_wall.json
sgp/sgp/doctype/pavers/pavers.json
sgp/sgp/doctype/ts_additional_costs/ts_additional_costs.json
sgp/sgp/utils/projects/site_work/site_work.py

total amount calculation in site work

Costing in site work

---

sgp/sgp/custom/py/workflow.py
sgp/sgp/function_calling.py
sgp/sgp/utils/hr/role/roles.py

New Role creation (Admin) for approve quotation workflow

workflow approval set to admin role

---

sgp/hooks.py
sgp/sgp/custom/js/delivery_note.js
sgp/sgp/custom/js/job_card.js
sgp/sgp/custom/js/quotation.js
sgp/sgp/custom/js/sales_order.js
sgp/sgp/custom/py/delivery_note.py
sgp/sgp/custom/py/job_card.py
sgp/sgp/custom/py/workflow.py

Jobcard to Stockentry

---

sgp/hooks.py
sgp/sgp/custom/js/delivery_note.js
sgp/sgp/custom/py/delivery_note.py
sgp/sgp/custom/py/stock_entry.py
sgp/sgp/utils/selling/delivery_note/delivery_note.py

Work order

---

sgp/sgp/custom/js/work_order.js
sgp/sgp/function_calling.py
sgp/sgp/utils/manufacturing/job_card/job_card.py
sgp/sgp/utils/manufacturing/work_order/work_order.py
sgp/sgp/utils/manufacturing/workstation/workstation.py
sgp/sgp/utils/stock/stock_entry/stock_entry.py

property setter and lable changes job card,work order,workstation,stock entry

property setter: job card,work order,workstation,stock entry

---

sgp/sgp/custom/js/work_order.js
sgp/sgp/custom/py/job_card.py

Msg thrown if no job created after the submission of jobcard

chore: alert msg if no operation in bom

---

sgp/sgp/custom/js/sales_order.js
sgp/sgp/custom/py/workflow.py

Quotation to Sales Order item table to Pavers or compound wall fetched.
[Screencast from 18-07-22 08:30:00 PM IST.webm](https://user-images.githubusercontent.com/95605398/179541036-8c86e7a9-bc0a-442a-882d-4b5a1304bb10.webm)
Workflow state changed

feat: SO paver, compound wall || Workflow customize

---

sgp/sgp/doctype/journal_receipt/journal_receipt.py

Cost center added in Journal Receipt

chore: Add cost_center field

---

sgp/sgp/doctype/journal_payment/journal_payment.py

Cost center in Journal Payment

cost_center for journal payment

---

sgp/sgp/custom/js/sales_order.js

Syntax error fixes

---

sgp/sgp/custom/py/defaults.py
sgp/sgp/function_calling.py

Contractor designation created

feat: employee designation

---

sgp/hooks.py
sgp/sgp/custom/js/job_card.js
sgp/sgp/custom/py/job_card.py
sgp/sgp/custom/py/stock_entry.py

auto submit and set the current completed qty in finest dialog box

modified:job card 

---

sgp/hooks.py
sgp/sgp/custom/js/job_card.js
sgp/sgp/custom/py/job_card.py
sgp/sgp/custom/py/sales_order.py
sgp/sgp/utils/manufacturing/job_card/job_card.py
sgp/sgp/utils/manufacturing/work_order/work_order.py

Removed UOM Conversion for Sales to work order, Workorder, Jobcard

Chores:Removed UOM Conversion

---

sgp/sgp/custom/py/salary_slip.py
sgp/sgp/doctype/ts_hr_employee_report/ts_hr_employee_report.json

salary slip item rate and amount

---

sgp/sgp/custom/js/site_work.js
sgp/sgp/function_calling.py
sgp/sgp/utils/Inventory/item_custom.py

Laying Cost fetch from Item in Site Work

feat: laying cost fetch from item

---

building_block_retail/building_block_retail/custom/js/delivery_note.js
building_block_retail/building_block_retail/custom/js/sales_invoice.js
building_block_retail/building_block_retail/custom/js/work_order.js
building_block_retail/building_block_retail/custom/py/job_card.py
building_block_retail/building_block_retail/custom/py/work_order.py
building_block_retail/hooks.py

Remove job card auto creation after work order submit
Remove unwanted buttons in some doctype

Chores: remove unwanted buttons and feature 

---

building_block_retail/backup/js/FileUploader.vue
building_block_retail/building_block_retail/custom/js/quotation.js
building_block_retail/building_block_retail/custom/py/quotation.py
building_block_retail/building_block_retail/utils/hr/role/roles.py

If the user has supervisor role, in attach file only camera option is visible
if it is not checked all option will be displayed
**With Supervisor**
**Without Supervisor**

feat: Attach file based on role

---

building_block_retail/building_block_retail/custom/js/delivery_note.js
building_block_retail/building_block_retail/custom/js/salary_slip.js
building_block_retail/building_block_retail/custom/js/sales_invoice.js
building_block_retail/building_block_retail/custom/js/sales_order.js
building_block_retail/building_block_retail/custom/py/defaults.py
building_block_retail/building_block_retail/custom/py/delivery_note.py
building_block_retail/building_block_retail/custom/py/salary_slip.py
building_block_retail/building_block_retail/custom/py/sales_order.py
building_block_retail/building_block_retail/custom/py/site_work.py
building_block_retail/building_block_retail/doctype/site_work_details/site_work_details.json
building_block_retail/building_block_retail/doctype/ts_loadman_cost/ts_loadman_cost.json
building_block_retail/building_block_retail/doctype/ts_loadman_cost/ts_loadman_cost.py
building_block_retail/building_block_retail/function_calling.py
building_block_retail/building_block_retail/utils/Inventory/item.py
building_block_retail/building_block_retail/utils/Inventory/item_custom.py
building_block_retail/building_block_retail/utils/hr/salary_slip/salary_slip.py
building_block_retail/building_block_retail/utils/projects/site_work/site_work.py
building_block_retail/building_block_retail/utils/selling/delivery_note/delivery_note.py
building_block_retail/building_block_retail/utils/selling/sales_invoice/sales_invoice_custom_fields.py
building_block_retail/building_block_retail/utils/selling/sales_order/sales_order.py
building_block_retail/hooks.py

feat: loadman cost in delivery note

---

building_block_retail/building_block_retail/custom/js/delivery_note.js
building_block_retail/building_block_retail/doctype/additional_costs/additional_costs.json
building_block_retail/building_block_retail/utils/hr/vehicle/vehicle.py
building_block_retail/building_block_retail/utils/selling/delivery_note/delivery_note.py

feat: delivery note map location

---

building_block_retail/building_block_retail/custom/js/sales_invoice.js
building_block_retail/building_block_retail/custom/py/sales_invoice.py
building_block_retail/building_block_retail/doctype/ts_job_worker_details/ts_job_worker_details.json
building_block_retail/building_block_retail/utils/selling/delivery_note/delivery_note.py
building_block_retail/hooks.py

Site work completion details fill to job worker details in site work

chores: sales invoice to site work

---

building_block_retail/building_block_retail/custom/js/delivery_note.js
building_block_retail/building_block_retail/custom/js/purchase_invoice.js
building_block_retail/building_block_retail/custom/js/purchase_order.js
building_block_retail/building_block_retail/custom/js/purchase_receipt.js
building_block_retail/building_block_retail/custom/js/sales_invoice.js
building_block_retail/building_block_retail/custom/js/sales_order.js
building_block_retail/building_block_retail/custom/py/item.py
building_block_retail/building_block_retail/doctype/ts_loadman_cost/ts_loadman_cost.json
building_block_retail/building_block_retail/report/delivery_note_transport_details/delivery_note_transport_details.json
building_block_retail/building_block_retail/report/stock_level_report/stock_level_report.json
building_block_retail/building_block_retail/utils/Inventory/item.py
building_block_retail/building_block_retail/utils/selling/delivery_note/delivery_note.py
building_block_retail/building_block_retail/workspace/inventory_reports/inventory_reports.json
building_block_retail/hooks.py

Vb Customization in Selling Buying and Inventory Module

vb customization

---

building_block_retail/building_block_retail/custom/js/delivery_note.js
building_block_retail/building_block_retail/doctype/ts_loadman_cost/ts_loadman_cost.json
building_block_retail/building_block_retail/utils/selling/delivery_note/delivery_note.py

loadman info
